title: FACTS.lab
email: facts.lab@rochester.edu
description: >- 
  Formal And CompuTational Semantics lab at the University of Rochester
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: Aaron Steven White
logo: /assets/images/facts-logo-blue.png
footer-logo: /assets/images/facts-logo-white.png
# Build settings

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll/scholar


# Permalinks
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /blog/:name/
  people:
    output: true
    permalink: /people/:name/
  projects:
    output: true
    permalink: /projects/:path/

  

highlighter: rouge

include_dir: "."

scholar:
  style: unified-style-sheet-for-linguistics.csl  
  source: assets/bibliography                 
  # bibliography: aaronstevenwhite.bib          
  details_link: true                             
  locale: en                                    


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
